[workspace]
authors = ["KhangDS&DL <gausseuler159357@gmail.com>"]
channels = ["conda-forge"]
name = "Code_FromZero2Hero"
platforms = ["osx-arm64", "linux-aarch64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"
numpy = ">=2.3.5,<3"
pandas = ">=2.3.3,<3"
matplotlib = ">=3.10.8,<4"
scikit-learn = ">=1.8.0,<2"
